# Generated by ChatGPT

import os
from pydub import AudioSegment
from google.cloud import texttospeech

def _mp3_2_wav (src_fpath: str, dst_fpath: str):
    AudioSegment.from_mp3(src_fpath).export(dst_fpath, format='wav')

def text_to_wav(text, output_file='output', language_code='en-US', gender=texttospeech.SsmlVoiceGender.NEUTRAL):
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "redditbot_sa_credentials.json"

    # Create a client
    client = texttospeech.TextToSpeechClient()

    # Set the text input
    input_text = texttospeech.SynthesisInput(text=text)

    # Set the voice parameters
    voice = texttospeech.VoiceSelectionParams(
        language_code=language_code, ssml_gender=gender
    )

    # Set the audio config
    audio_config = texttospeech.AudioConfig(
        audio_encoding=texttospeech.AudioEncoding.MP3
    )

    # Generate the speech
    response = client.synthesize_speech(
        input=input_text, voice=voice, audio_config=audio_config
    )

    # Write the response to the output file
    with open(f'{output_file}.mp3', 'wb') as out:
        out.write(response.audio_content)

    _mp3_2_wav(f'{output_file}.mp3', f'{output_file}')
    os.remove(f'{output_file}.mp3')

    return output_file